package vistas;

import accesoadatos.ProductoData;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JFrame;
import javax.swing.UIManager;

public class MenuView extends javax.swing.JFrame {
    
    public MenuView() {
        initComponents();
        listNotificacion.setVisible(false);
        notificacion();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admDetalleCompra1 = new vista.adm.AdmDetalleCompra();
        jPanel1 = new javax.swing.JPanel();
        tabMenu = new javax.swing.JTabbedPane();
        admProveedor1 = new vista.adm.AdmProveedor();
        admProducto1 = new vista.adm.AdmProducto();
        admCompra1 = new vista.adm.AdmCompra();
        admDetalleCompra1 = new vista.adm.AdmDetalleCompra();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNotificaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNotificacion = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tabMenu.setBackground(new java.awt.Color(255, 255, 255));
        tabMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabMenu.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tabMenu.addTab("Proveedores", new javax.swing.ImageIcon(getClass().getResource("/vista/img/usuario.png")), admProveedor1); // NOI18N
        tabMenu.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/vista/img/caja-alt.png")), admProducto1); // NOI18N
        tabMenu.addTab("Compras", new javax.swing.ImageIcon(getClass().getResource("/vista/img/carrito-de-compras.png")), admCompra1); // NOI18N
        tabMenu.addTab("tab4", admDetalleCompra1);

        jPanel1.add(tabMenu, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.setPreferredSize(new java.awt.Dimension(147, 75));

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ProveMax");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(124, 15));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbNotificaciones.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbNotificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNotificaciones.setText("Notificaciones");
        lbNotificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNotificacionesMouseClicked(evt);
            }
        });

        listNotificacion.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listNotificacion);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNotificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNotificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbNotificacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNotificacionesMouseClicked
        if (listNotificacion.isVisible()) {
            listNotificacion.setVisible(false);
        } else {
            
            listNotificacion.setVisible(true);
        }
    }//GEN-LAST:event_lbNotificacionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.adm.AdmCompra admCompra1;
    private vista.adm.AdmDetalleCompra admDetalleCompra1;
    private vista.adm.AdmProducto admProducto1;
    private vista.adm.AdmProveedor admProveedor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbNotificaciones;
    private javax.swing.JList<String> listNotificacion;
    private javax.swing.JTabbedPane tabMenu;
    // End of variables declaration//GEN-END:variables

    private void notificacion() {
        ProductoData prodData = new ProductoData();
        
        //Cambia el icono si hay notificaciones
        if (prodData.cantidadProducto().size() > 1) {
            lbNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/punto-de-sobre.png")));
        } else {
            lbNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/sobre.png")));
        }
        
        //Crea un Vector y le asigna la dimension segun el size del ArrayList
        String[] listData = new String[prodData.cantidadProducto().size()];
        
        //Convierte el ArrayList a Vector
        listData = prodData.cantidadProducto().toArray(listData);
        
        listNotificacion.setListData(listData);
    }
}
