package vista;

import accesoadatos.ProveedorData;
import entidad.Proveedor;
import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

public class ProveedorVista extends javax.swing.JPanel {

    private DefaultTableModel tableModel = new DefaultTableModel() {
        public boolean isCellEditable(int r, int c) {
            return false;
        }
    };
    
    private ProveedorData proveData = new ProveedorData();
    
    public ProveedorVista() {
        initComponents();
        cargarModeloTabla();
        refrescarTabla();
        agruparRadioButton();
        
        InputMap map1 = txtTelefono.getInputMap(JTextField.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnMostrarProveedores = new javax.swing.JRadioButton();
        btnActivo = new javax.swing.JRadioButton();
        btnInactivo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        panelSuperior = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProveedor = new javax.swing.JTable();

        setBackground(new java.awt.Color(237, 230, 219));

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));
        panelLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelLateral.setPreferredSize(new java.awt.Dimension(342, 592));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(149, 165, 131));
        txtCodigo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCodigo.setPreferredSize(new java.awt.Dimension(240, 25));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Razón social");

        txtRazonSocial.setBackground(new java.awt.Color(149, 165, 131));
        txtRazonSocial.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtRazonSocial.setForeground(new java.awt.Color(255, 255, 255));
        txtRazonSocial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtRazonSocial.setPreferredSize(new java.awt.Dimension(240, 25));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Domicilio");

        txtDomicilio.setBackground(new java.awt.Color(149, 165, 131));
        txtDomicilio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        txtDomicilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtDomicilio.setPreferredSize(new java.awt.Dimension(240, 25));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono");

        txtTelefono.setBackground(new java.awt.Color(149, 165, 131));
        txtTelefono.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtTelefono.setPreferredSize(new java.awt.Dimension(240, 25));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(162, 179, 139));
        btnLimpiarCampos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/borrador.png"))); // NOI18N
        btnLimpiarCampos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 179, 139)));
        btnLimpiarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarCampos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpiarCampos.setPreferredSize(new java.awt.Dimension(46, 46));
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(162, 179, 139));
        btnRegistrar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/agregar-usuario.png"))); // NOI18N
        btnRegistrar.setToolTipText("Registrar un nuevo proveedor");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 179, 139)));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(36, 36));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(162, 179, 139));
        btnModificar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnModificar.setForeground(java.awt.Color.white);
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/lapiz-de-usuario.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar proveedor");
        btnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 179, 139)));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setPreferredSize(new java.awt.Dimension(36, 36));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBaja.setBackground(new java.awt.Color(162, 179, 139));
        btnBaja.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnBaja.setForeground(java.awt.Color.white);
        btnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/quitar-usuario.png"))); // NOI18N
        btnBaja.setToolTipText("Dar de baja un proveedor");
        btnBaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 179, 139)));
        btnBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBaja.setPreferredSize(new java.awt.Dimension(36, 36));
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnAlta.setBackground(new java.awt.Color(162, 179, 139));
        btnAlta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnAlta.setForeground(java.awt.Color.white);
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/comprobacion-de-usuario.png"))); // NOI18N
        btnAlta.setToolTipText("Dar de alta un proveedor");
        btnAlta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 179, 139)));
        btnAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlta.setPreferredSize(new java.awt.Dimension(36, 36));
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnMostrarProveedores.setBackground(new java.awt.Color(162, 179, 139));
        btnMostrarProveedores.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnMostrarProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarProveedores.setSelected(true);
        btnMostrarProveedores.setText("Mostrar todos los proveedores");
        btnMostrarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProveedoresActionPerformed(evt);
            }
        });

        btnActivo.setBackground(new java.awt.Color(162, 179, 139));
        btnActivo.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnActivo.setText("Mostrar proveedores activos");
        btnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivoActionPerformed(evt);
            }
        });

        btnInactivo.setBackground(new java.awt.Color(162, 179, 139));
        btnInactivo.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnInactivo.setForeground(new java.awt.Color(255, 255, 255));
        btnInactivo.setText("Mostrar proveedores inactivos");
        btnInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Consultas");

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(panelLateralLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInactivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInactivo)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        panelSuperior.setBackground(new java.awt.Color(237, 230, 219));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setText("Buscar por razón social");

        txtBuscar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(300, 26));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tableProveedor.setBackground(new java.awt.Color(237, 230, 219));
        tableProveedor.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProveedor.setSelectionBackground(new java.awt.Color(162, 179, 139));
        tableProveedor.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableProveedor.getTableHeader().setReorderingAllowed(false);
        tableProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableProveedorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableProveedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            if (txtRazonSocial.getText().isEmpty() || txtDomicilio.getText().isEmpty() || txtTelefono.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos.", "Error al registrar", HEIGHT);
            } else {
                Proveedor proveedor = new Proveedor(
                        txtRazonSocial.getText(),
                        txtDomicilio.getText(),
                        Integer.parseInt(txtTelefono.getText()),
                        true
                ); //end Proveedor constructor

                proveData.nuevoProveedor(proveedor);
                refrescarTabla();
                limpiarCampos();
                btnMostrarProveedores.setSelected(true);
                
                // Actualiza los ComboBox de las otras vistas
                CompraVista.cargarComboProveedor();
                DetalleCompraVista.cargarComboProveedor();
            }//end if-else
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El teléfono ingresado es invalido.", "Error al registrar", HEIGHT);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        try {
            int row = tableProveedor.getSelectedRow();
            int id = (int) tableProveedor.getValueAt(row, 0);
        
            if (row != -1 && (String) tableProveedor.getValueAt(row, 4) == "Inactivo") {
                proveData.darAltaProveedor(id);
            } else {
                JOptionPane.showMessageDialog(this, "El proveedor ya está dado de alta.");
            }
            refrescarTabla();
            btnMostrarProveedores.setSelected(true);
            
            // Actualiza los ComboBox de las otras vistas
            CompraVista.cargarComboProveedor();
            DetalleCompraVista.cargarComboProveedor();
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún proveedor.");
        } finally {
            limpiarCampos();
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        try {
            int row = tableProveedor.getSelectedRow();
            int id = (int) tableProveedor.getValueAt(row, 0);
        
            if (row != -1 && (String) tableProveedor.getValueAt(row, 4) == "Activo") {
                proveData.cambiarEstadoProveedor(id);
            } else {
                JOptionPane.showMessageDialog(this, "El proveedor ya está dado de baja.");
            }
            refrescarTabla();
            limpiarCampos();
            btnMostrarProveedores.setSelected(true);
            
            // Actualiza los ComboBox de las otras vistas
            CompraVista.cargarComboProveedor();
            DetalleCompraVista.cargarComboProveedor();
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún proveedor para dar de baja.");
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        tableModel.setRowCount(0); // Limpia la tabla.
        buttonGroup1.clearSelection();

        String textoBuscar = txtBuscar.getText().toLowerCase(); // Convierte el texto de busqueda a minuscula.
        
        for (Proveedor proveedor : proveData.listarProveedor(2)) {
            String razonSocial = proveedor.getRazonSocial().toLowerCase(); // Convierte el texto de la base de datos a minuscula.
            
            if (razonSocial.startsWith(textoBuscar)) {
                String estado = cambiarEstadoAString(proveedor);
                tableModel.addRow(new Object[]{
                    proveedor.getIdProveedor(),
                    proveedor.getRazonSocial(),
                    proveedor.getDomicilio(),
                    proveedor.getTelefono(),
                    estado
                });
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            int seleccionar = tableProveedor.getSelectedRow();

            int codigo = Integer.parseInt(txtCodigo.getText());
            String razonSocial = txtRazonSocial.getText();
            String domicilio = txtDomicilio.getText();
            int telefono = Integer.parseInt(txtTelefono.getText());
            boolean estado = cambiarEstadoABoolean((String) tableModel.getValueAt(seleccionar, 4));

            Proveedor prov = new Proveedor(codigo, razonSocial, domicilio, telefono, estado);
            proveData.modificarProveedor(prov);

            refrescarTabla();
            limpiarCampos();
            btnMostrarProveedores.setSelected(true);

            // Actualiza los ComboBox de las otras vistas
            CompraVista.cargarComboProveedor();
            DetalleCompraVista.cargarComboProveedor();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún proveedor para modificar.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void tableProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProveedorMousePressed
        int seleccionar = tableProveedor.getSelectedRow();
        
        if(seleccionar != -1){
            int codigo = (int)tableModel.getValueAt(seleccionar, 0);
            String razonSocial = tableModel.getValueAt(seleccionar, 1).toString();
            String domicilio = tableModel.getValueAt(seleccionar, 2).toString();
            int telefono = (int)tableModel.getValueAt(seleccionar, 3);

            txtCodigo.setText(codigo + "");
            txtRazonSocial.setText(razonSocial);
            txtDomicilio.setText(domicilio);
            txtTelefono.setText(telefono + "");
        }
    }//GEN-LAST:event_tableProveedorMousePressed

    private void btnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivoActionPerformed
        tableModel.setRowCount(0); // Limpia la tabla.

        for (Proveedor proveedor : proveData.listarProveedorEstado(1)) {
            String estado = cambiarEstadoAString(proveedor);
            tableModel.addRow(new Object[]{
                proveedor.getIdProveedor(),
                proveedor.getRazonSocial(),
                proveedor.getDomicilio(),
                proveedor.getTelefono(),
                estado
            });
        }
    }//GEN-LAST:event_btnActivoActionPerformed

    private void btnInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivoActionPerformed
        tableModel.setRowCount(0); // Limpia la tabla.

        for (Proveedor proveedor : proveData.listarProveedorEstado(0)) {
            String estado = cambiarEstadoAString(proveedor);
            tableModel.addRow(new Object[]{
                proveedor.getIdProveedor(),
                proveedor.getRazonSocial(),
                proveedor.getDomicilio(),
                proveedor.getTelefono(),
                estado
            });
        }
    }//GEN-LAST:event_btnInactivoActionPerformed

    private void btnMostrarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProveedoresActionPerformed
        refrescarTabla();
    }//GEN-LAST:event_btnMostrarProveedoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnActivo;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JRadioButton btnInactivo;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JRadioButton btnMostrarProveedores;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tableProveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void cargarModeloTabla() {
        tableModel.addColumn("CÓDIGO");
        tableModel.addColumn("RAZÓN SOCIAL");
        tableModel.addColumn("DOMICILIO");
        tableModel.addColumn("TELÉFONO");
        tableModel.addColumn("ESTADO");
        tableProveedor.setModel(tableModel);
    }
    
    private void refrescarTabla() {
        tableModel.setRowCount(0); // Limpia la tabla.

        for (Proveedor proveedor : proveData.listarProveedor(2)) {
            String estado = cambiarEstadoAString(proveedor);
            tableModel.addRow(new Object[]{
                proveedor.getIdProveedor(),
                proveedor.getRazonSocial(),
                proveedor.getDomicilio(),
                proveedor.getTelefono(),
                estado
            });
        }
    }
    
    private boolean cambiarEstadoABoolean(String estado) {
        boolean estadoBool = false;
        if (estado == "Activo") {
            estadoBool = true;
        } else if (estado == "Inactivo") {
            estadoBool = false;
        }
        return estadoBool;
    }
    
    private String cambiarEstadoAString(Proveedor proveedor) {
        String estado;
        if (proveedor.isEstado()) {
            estado = "Activo";
        } else {
            estado = "Inactivo";
        }
        return estado;
    }
    
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtRazonSocial.setText("");
        txtDomicilio.setText("");
        txtTelefono.setText("");
    }
    
    private void agruparRadioButton() {
        buttonGroup1.add(btnMostrarProveedores);
        buttonGroup1.add(btnActivo);
        buttonGroup1.add(btnInactivo);
    }
}
